:chapter-label:
:icons: font
:lang: en
:sectanchors:
:sectnums:
:sectnumlevels: 1
:source-highlighter: highlightjs
:toc:
:toclevels: 2

:author: isuke
:email: isuke770@gmail.com

= postcss-ghost-utils image:https://travis-ci.org/isuke/postcss-ghost-utils.svg?branch=master["Build Status", link="https://travis-ci.org/isuke/postcss-ghost-utils"]

postcss-ghost-utils is a https://github.com/postcss/postcss[PostCSS] plugin.

This plugin can give you useful css syntax.
It is not include old css technique (ex. clearfix).

https://codepen.io/isuke/pen/xywgVx[Try it on CodePen]

== Usage

[source,sh]
----
$ npm install -D postcss postcss-ghost-utils
# or
$ yarn add -D postcss postcss-ghost-utils
----

[source,js]
.postcss.config.js
----
module.exports = {
  plugins: [
    require('postcss-ghost-utils')
  ]
}
----

=== Use on CodePen

Open JavaScript setting of your pen, and add follows a URL.

* latest: `https://codepen.io/isuke/pen/WaQoKE`

== Rule List

=== font-size-line-height

[source,css]
.input
----
.one {
  @ghost font-size-line-height(16px, 2px);
}
----

[source,css]
.output
----
.one {
  font-size: 16px;
  line-height: calc(16px + 2px * 2);
}
----

=== new-line

[source,css]
.input
----
.one {
  @ghost new-line;
}
----

[source,css]
.output
----
.one {
  white-space: pre-wrap;
  word-wrap: break-word;
}
----

=== margin-left-right

[source,css]
.input
----
.one {
  @ghost margin-left-right(16px);
}
----

[source,css]
.output
----
.one {
  margin-left: 16px;
  margin-right: 16px;
}
----

=== margin-top-bottom

[source,css]
.input
----
.one {
  @ghost margin-top-bottom(16px);
}
----

[source,css]
.output
----
.one {
  margin-top: 16px;
  margin-bottom: 16px;
}
----

=== padding-left-right

[source,css]
.input
----
.one {
  @ghost padding-left-right(16px);
}
----

[source,css]
.output
----
.one {
  padding-left: 16px;
  padding-right: 16px;
}
----

=== padding-top-bottom

[source,css]
.input
----
.one {
  @ghost padding-top-bottom(16px);
}
----

[source,css]
.output
----
.one {
  padding-top: 16px;
  padding-bottom: 16px;
}
----

=== border-left-right

[source,css]
.input
----
.one {
  @ghost border-left-right(2px solid black);
}
----

[source,css]
.output
----
.one {
  border-left: 2px solid black;
  border-right: 2px solid black;
}
----

=== border-top-bottom

[source,css]
.input
----
.one {
  @ghost border-top-bottom(2px solid black);
}
----

[source,css]
.output
----
.one {
  border-top: 2px solid black;
  border-bottom: 2px solid black;
}
----

=== border-top-radius

[source,css]
.input
----
.one {
  @ghost border-top-radius(4px);
}

.two {
  @ghost border-top-radius(4px 2px);
}
----

[source,css]
.output
----
.one {
  border-top-left-radius: 4px;
  border-top-right-radius: 4px;
}

.two {
  border-top-left-radius: 4px 2px;
  border-top-right-radius: 4px 2px;
}
----

=== border-bottom-radius

[source,css]
.input
----
.one {
  @ghost border-bottom-radius(4px);
}

.two {
  @ghost border-bottom-radius(4px 2px);
}
----

[source,css]
.output
----
.one {
  border-bottom-left-radius: 4px;
  border-bottom-right-radius: 4px;
}

.two {
  border-bottom-left-radius: 4px 2px;
  border-bottom-right-radius: 4px 2px;
}
----

=== border-left-radius

[source,css]
.input
----
.one {
  @ghost border-left-radius(4px);
}

.two {
  @ghost border-left-radius(4px 2px);
}
----

[source,css]
.output
----
.one {
  border-top-left-radius: 4px;
  border-bottom-left-radius: 4px;
}

.two {
  border-top-left-radius: 4px 2px;
  border-bottom-left-radius: 4px 2px;
}
----

=== border-right-radius

[source,css]
.input
----
.one {
  @ghost border-right-radius(4px);
}

.two {
  @ghost border-right-radius(4px 2px);
}
----

[source,css]
.output
----
.one {
  border-top-right-radius: 4px;
  border-bottom-right-radius: 4px;
}

.two {
  border-top-right-radius: 4px 2px;
  border-bottom-right-radius: 4px 2px;
}
----

=== size

[source,css]
.input
----
.one {
  @ghost size(160px);
}

.two {
  @ghost size(160px, 240px);
}
----

[source,css]
.output
----
.one {
  width: 160px;
  height: 160px;
}

.two {
  width: 160px;
  height: 240px;
}
----

=== circle

[source,css]
.input
----
.one {
  @ghost circle(200px);
  background-color: #ff0000;
  border: 10px solid #ffffff;
}
----

[source,css]
.output
----
.one {
  width: 200px;
  height: 200px;
  border-radius: 50%;
  background-color: #ff0000;
  border: 10px solid #ffffff;
}
----

== Experimental Rule List

The following rules may not work with not pure css ex) LESS, SASS.

=== all-buttons

[source,css]
.input
----
@ghost all-buttons {
  background-color: transparent;
  border: none;
  cursor: pointer;
  outline: 0;
}

@ghost all-buttons(hover) {
  transform: translateY(-2px);
  box-shadow: 0 2px 2px rgba(0, 0, 0, 0.2);
}

@ghost all-buttons(active) {
  transform: none;
  box-shadow: none;
}

@ghost all-buttons(focus) {
  transform: translateY(-2px);
  box-shadow: 0 2px 2px rgba(0, 0, 0, 0.2);
}
----

[source,css]
.output
----
button, [type='button'], [type='reset'], [type='submit'] {
  background-color: transparent;
  border: none;
  cursor: pointer;
  outline: 0;
}

button:hover, [type='button']:hover, [type='reset']:hover, [type='submit']:hover {
  transform: translateY(-2px);
  box-shadow: 0 2px 2px rgba(0, 0, 0, 0.2);
}

button:active, [type='button']:active, [type='reset']:active, [type='submit']:active {
  transform: none;
  box-shadow: none;
}

button:focus, [type='button']:focus, [type='reset']:focus, [type='submit']:focus {
  transform: translateY(-2px);
  box-shadow: 0 2px 2px rgba(0, 0, 0, 0.2);
}
----
